name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello from github action, start deploy dev to ec2"
            cd /home/ubuntu/puzzle-together
            git switch dev
            git pull
            cd client
            npm install
            npm run build
            cd ../server
            npm install
            npx pm2 restart app